module.exports = {
  "name": "SINGLE_STOCK",
  "type": "SINGLE_STOCK",
  "createdDate": "20221207T022825Z",
  "lastUpdateDate": "20221207T022825Z",
  "lastUsedDate": "20221207T022825Z",
  "input": [],
  "excel": [],
  "viewVisble": {
    "INSTRUMENT_CHARACTERISTICS": true,
    "HISTORICAL_INTRADAY_PROFILES": true,
    "TRADE_SCHEDULE_ESTIMATE": true,
    "OPTIMIZED_PARAMETERS": true
  },
  "layout": [
    {
      "w": 6,
      "h": 12,
      "x": 0,
      "y": 0,
      "i": "INSTRUMENT_CHARACTERISTICS",
      "minW": 6,
      "minH": 12,
      "moved": false,
      "static": false,
      "isResizable": true,
      "resizeHandles": ["s", "e", "se"],
    },
    {
      "w": 7,
      "h": 12,
      "x": 6,
      "y": 0,
      "i": "MARKET_CONDITION_INDICATORS",
      "minW": 7,
      "minH": 12,
      "moved": false,
      "static": false,
      "isResizable": true,
      "resizeHandles": ["s", "e", "se"],
    },
    {
      "w": 7,
      "h": 19,
      "x": 13,
      "y": 0,
      "i": "OPTIMIZED_PARAMETERS",
      "minW": 7,
      "minH": 19,
      "moved": false,
      "static": false,
      "isResizable": true,
      "resizeHandles": ["s", "e", "se"],
    },
    {
      "w": 9,
      "h": 14,
      "x": 0,
      "y": 26,
      "i": "TRADE_SCHEDULE_ESTIMATE",
      "minW": 8,
      "minH": 14,
      "moved": false,
      "static": false,
      "isResizable": true,
      "resizeHandles": ["s", "e", "se"],
    },
    {
      "w": 9,
      "h": 14,
      "x": 0,
      "y": 12,
      "i": "HISTORICAL_INTRADAY_PROFILES",
      "minW": 9,
      "minH": 14,
      "moved": false,
      "static": false,
      "isResizable": true,
      "resizeHandles": ["s", "e", "se"],
    }
  ],
  "permission": 'PRIVATE'
}