module.exports = {
    "name": "PORTFOLIO",
    "type": "PORTFOLIO",
    "createdDate": "20221207T022825Z",
    "lastUpdateDate": "20221207T022825Z",
    "lastUsedDate": "20221207T022825Z",
    "input": [],
    "excel": [],
    "viewVisble": {
        "HISTORICAL_INTRADAY_PROFILES": true,
        "TRADE_SCHEDULE_ESTIMATE": true,
        "OPTIMIZED_PARAMETERS": true,
        "PORTFOLIO_SUMMARY": true,
        "PORTFOLIO_BREAKDOWN": true
    },
    "layout": [
        {
            "w": 7,
            "h": 13,
            "x": 6,
            "y": 0,
            "i": "MARKET_CONDITION_INDICATORS",
            "minW": 7,
            "minH": 13,
            "moved": false,
            "static": false,
            "isResizable": true,
            "resizeHandles": ["s", "e", "se"],
        },
        {
            "w": 7,
            "h": 20,
            "x": 13,
            "y": 0,
            "i": "OPTIMIZED_PARAMETERS",
            "minW": 7,
            "minH": 20,
            "moved": false,
            "static": false,
            "isResizable": true,
            "resizeHandles": ["s", "e", "se"],
        },
        {
            "w": 6,
            "h": 12,
            "x": 0,
            "y": 7,
            "i": "PORTFOLIO_BREAKDOWN",
            "minW": 6,
            "minH": 12,
            "moved": false,
            "static": false,
            "isResizable": true,
            "resizeHandles": ["s", "e", "se"],
        },
        {
            "w": 6,
            "h": 15,
            "x": 0,
            "y": 19,
            "i": "TRADE_SCHEDULE_ESTIMATE",
            "minW": 6,
            "minH": 15,
            "moved": false,
            "static": false,
            "isResizable": true,
            "resizeHandles": ["s", "e", "se"],
        },
        {
            "w": 14,
            "h": 15,
            "x": 6,
            "y": 20,
            "i": "HISTORICAL_INTRADAY_PROFILES",
            "minW": 9,
            "minH": 14,
            "moved": false,
            "static": false,
            "isResizable": true,
            "resizeHandles": ["s", "e", "se"],
        },
        {
            "w": 6,
            "h": 7,
            "x": 0,
            "y": 0,
            "i": "PORTFOLIO_SUMMARY",
            "minW": 6,
            "minH": 7,
            "moved": false,
            "static": false,
            "isResizable": true,
            "resizeHandles": ["s", "e", "se"],
        }
    ],
    "permission": 'PRIVATE'
}
